export { default as FooterFourColumnSimple } from './4ColumnSimple';
export { default as FooterFourColumnSimpleDark } from './4ColumnSimpleDark';
export { default as FooterFourColumnWithCompanyMission } from './4ColumnWithCompanyMission';
export { default as FooterFourColumnWithNewsletter } from './4ColumnWithNewsletter';
export { default as FooterFourColumnWithNewsletterBelow } from './4ColumnWithNewsletterBelow';
export { default as FooterFourColumnWithNewsletterBelowDark } from './4ColumnWithNewsletterBelowDark';
export { default as FooterFourColumnWithNewsletterDark } from './4ColumnWithNewsletterDark';
export { default as FooterSimpleCentered } from './SimpleCentered';
export { default as FooterSocialLinksOnly } from './SocialLinksOnly';
